# Generated by Django 5.2.4 on 2025-08-26 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_community',
            field=models.CharField(default='public', max_length=100),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_port',
            field=models.PositiveIntegerField(default=161),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
