# Generated by Django 5.2.4 on 2025-08-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
